-- ═══════════════════════════════════════════════════════
-- SuccessOS Diary Import - 30 days
-- Generated by import-diary.ts
-- Date: 2026-03-12T16:32:44.435Z
-- ═══════════════════════════════════════════════════════

BEGIN TRANSACTION;

-- ── Daily Entries ──────────────────────────────────────

-- Día 1: Lunes 10/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-10',
  '01:30', '08:15', 4, '7:50 / Me levanté 8:15. Apreté snooze dos veces.',
  6, NULL,
  1, 'Pecho y tríceps', 60, 'Pecho y tríceps. Press plano hasta 60kg (RM). Aperturas 14kg. Fondos 3x10. Press francés 25kg.',
  '[{"meal":"desayuno","desc":"comprar). desayuné tostadas con manteca mirando el celu, res"},{"meal":"almuerzo","desc":"almorcé fideos con tuco que había hecho mi vieja el día ante"},{"meal":"cena","desc":"seguidas. cené milanesa con puré que preparó mi vieja. vi un rato twit"}]', 6, 'desayuno: comprar). desayuné tostadas con manteca mirando el celu, res; almuerzo: almorcé fideos con tuco que había hecho mi vieja el día ante; cena: seguidas. cené milanesa con puré que preparó mi vieja. vi un rato twit',
  7, 'estable', 'Me acosté 1:30. Calor tremendo todo el día, 38°C en Santa Fe. Día medio pelo.',
  1.5, NULL, 1, NULL, 'Facu: Estudié Análisis ~1.5hs reales. 3 ejercicios de límites resueltos, 1 pendiente (epsilon-delta). | Gorila: Vi video de cold outreach, me quedó la idea de aplicarlo. Nada concreto.',
  'Amigos, Salida', NULL,
  '{"screens_late":true}', 'Pantallas/redes sociales excesivas',
  6, 6,
  '2026-03-12T16:32:44.436Z', '2026-03-12T16:32:44.436Z'
);

-- Día 2: Martes 11/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-11',
  '02:00', '08:30', 2, '7:50 / Me levanté 8:30. Dormí mal por el calor, me desperté dos veces a la noche.',
  7, NULL,
  0, NULL, NULL, 'descanso.',
  '[{"meal":"desayuno","desc":"desayuné mate con galletitas de agua sentado en la"},{"meal":"almuerzo","desc":"almorcé arroz con pollo al horno que había sobrado. después"},{"meal":"cena","desc":"cené empanadas de carne que trajo mi viejo. vi twitch un rat"}]', 6, 'desayuno: desayuné mate con galletitas de agua sentado en la; almuerzo: almorcé arroz con pollo al horno que había sobrado. después; cena: cené empanadas de carne que trajo mi viejo. vi twitch un rat',
  7, 'estable', 'Día medio improductivo en lo académico. Avancé con Gorila al menos.',
  1.5, NULL, 1, NULL, 'Facu: Álgebra ~1.5hs. Espacios vectoriales, 1 ejercicio resuelto, 1 sin resolver. Leí teoría. | Gorila: Probé audit automático con Claude Code en sitio de constructora. Le mandé resultados a mi socio. Ava',
  'Salida', NULL,
  '{"screens_late":true}', 'Pantallas/redes sociales excesivas',
  4, 4,
  '2026-03-12T16:32:44.437Z', '2026-03-12T16:32:44.437Z'
);

-- Día 3: Miércoles 12/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-12',
  '23:30', '07:55', 5, '7:50 / 7:55. Me levanté de una, raro en mí.',
  8, NULL,
  1, 'Espalda y bíceps', 60, 'Espalda y bíceps. Remo 50kg, jalón 45kg, peso muerto rumano 60kg, curl Z 25kg, curl martillo 10kg.',
  '[{"meal":"desayuno","desc":"cremoso, desayuné tranquilo. a las 8:30 ya estaba sentado e"},{"meal":"almuerzo","desc":"almorcé milanesa con ensalada de tomate y lechuga. a las 14"},{"meal":"cena","desc":"me bañé, cené unas tostadas con jamón y queso nomás porque no tenía g"}]', 7, 'desayuno: cremoso, desayuné tranquilo. a las 8:30 ya estaba sentado e; almuerzo: almorcé milanesa con ensalada de tomate y lechuga. a las 14; cena: me bañé, cené unas tostadas con jamón y queso nomás porque no tenía g',
  8, 'motivado', 'Día productivo de verdad, ojalá fueran todos así. Me dormí temprano y bien.',
  5, NULL, 0, NULL, 'Facu: Análisis 2hs (resolví epsilon-delta + 3 ej de límites trig). Álgebra 3hs con Facu (subespacios, comb | Gorila: Nada hoy.',
  'Salida', NULL,
  NULL, NULL,
  9, 9,
  '2026-03-12T16:32:44.437Z', '2026-03-12T16:32:44.437Z'
);

-- Día 4: Jueves 13/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-13',
  '01:00', '08:40', 5, '7:50 / 8:40. Me costó horrores salir de la cama, estaba dolorido del gym.',
  5, NULL,
  1, 'Piernas', 60, 'Piernas. Sentadilla 70kg 4x8, prensa 120kg 3x12, extensiones 35kg, curl femoral 30kg, gemelos 60kg.',
  '[{"meal":"desayuno","desc":"desayuné mate solo en la cocina, mi vieja me dejó"},{"meal":"almuerzo","desc":"ieja hizo guiso de lentejas, comí dos platos porque tenía un hambre te"},{"meal":"cena","desc":"whatsapp. cené pizza que pidió mi viejo, comimos juntos viendo la tele"}]', 5, 'desayuno: desayuné mate solo en la cocina, mi vieja me dejó; almuerzo: ieja hizo guiso de lentejas, comí dos platos porque tenía un hambre te; cena: whatsapp. cené pizza que pidió mi viejo, comimos juntos viendo la tele',
  6, 'estable', 'Piernas destruidas. Estudio flojo pero avancé con prospección de Gorila.',
  0, NULL, 0, NULL, 'Facu: Flojo. Intenté Análisis pero no me concentré. Un ejercicio de continuidad dudoso. | Gorila: Scrapeo manual de estudios de arq en Google Maps. Encontré 15 prospectos, mandé 1 mensaje de WhatsAp',
  'Salida, Pizza', NULL,
  NULL, NULL,
  6, 6,
  '2026-03-12T16:32:44.437Z', '2026-03-12T16:32:44.437Z'
);

-- Día 5: Viernes 14/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-14',
  NULL, '09:30', 6, 'Sin alarma / 9:30. Me desperté solo con la luz del sol.',
  6, NULL,
  0, NULL, NULL, 'no fui, viernes libre.',
  '[{"meal":"desayuno","desc":"laburar, desayuné con mate unos vigilantes y cañoncitos con"},{"meal":"almuerzo","desc":"morcilla, ensalada rusa que hizo mi vieja. nos quedamos en la mesa cha"}]', 6, 'desayuno: laburar, desayuné con mate unos vigilantes y cañoncitos con; almuerzo: morcilla, ensalada rusa que hizo mi vieja. nos quedamos en la mesa cha',
  7, 'estable', 'Viernes de desconexión. Asado familiar + salida con amigos. Lo necesitaba.',
  0, NULL, 1, NULL, 'Facu: Cero. Ni abrí un apunte. | Gorila: Nada.',
  'Asado, Amigos, Salida, Familia', NULL,
  '{"screens_late":true,"alcohol":true}', 'Pantallas/redes sociales excesivas; Alcohol',
  3, 3,
  '2026-03-12T16:32:44.438Z', '2026-03-12T16:32:44.438Z'
);

-- Día 6: Sábado 15/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-15',
  '01:00', '10:45', 6, 'Sin alarma / 10:45. Me costó despegarme de la almohada.',
  5, NULL,
  0, NULL, NULL, 'no fui, sábado libre.',
  '[{"meal":"desayuno","desc":"tó igual. desayuné tipo 11 con mate amargo y unas tostadas p"},{"meal":"almuerzo","desc":"almorcé ravioles de ricota con mi familia. después me puse a"},{"meal":"cena","desc":"a las 23. cené un sánguche de milanesa. después me quedé viendo netfli"}]', 6, 'desayuno: tó igual. desayuné tipo 11 con mate amargo y unas tostadas p; almuerzo: almorcé ravioles de ricota con mi familia. después me puse a; cena: a las 23. cené un sánguche de milanesa. después me quedé viendo netfli',
  6, 'estable', 'Día de descanso total. Mecánica del Fit y videíto de prueba.',
  0, NULL, 0, NULL, 'Facu: Cero. | Gorila: Nada.',
  'Asado, Amigos, Familia', NULL,
  '{"alcohol":true}', 'Alcohol',
  5, 5,
  '2026-03-12T16:32:44.438Z', '2026-03-12T16:32:44.438Z'
);

-- Día 7: Domingo 16/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-16',
  '23:00', '08:35', 6, '8:30 / 8:35. Me levanté rápido porque tenía que ir a misa.',
  6, NULL,
  0, NULL, NULL, 'no fui, domingo.',
  '[{"meal":"desayuno","desc":"me vestí, desayuné un mate rápido con unas galletitas y sali"},{"meal":"cena","desc":"cené liviano, una ensalada de lechuga, tomate y zanahoria. d"}]', 7, 'desayuno: me vestí, desayuné un mate rápido con unas galletitas y sali; cena: cené liviano, una ensalada de lechuga, tomate y zanahoria. d',
  7, 'estable', 'Domingo clásico. Misa, familia, estudio. Recargué pilas para la semana.',
  2.5, NULL, 0, NULL, 'Facu: Análisis ~2.5hs. Derivadas: regla de la cadena (5 ej), parciales (2 ej). Bien. | Gorila: Nada.',
  'Misa, Familia', NULL,
  NULL, NULL,
  6, 6,
  '2026-03-12T16:32:44.438Z', '2026-03-12T16:32:44.438Z'
);

-- Día 8: Lunes 17/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-17',
  NULL, '08:00', 7, '7:50 / 8:00. Me levanté bien, había dormido como 9 horas.',
  7, NULL,
  1, 'Pecho y tríceps', 60, 'Pecho y tríceps. Press plano 65kg (nuevo peso). Inclinado 18kg. Aperturas polea. Tríceps polea + fondos.',
  '[{"meal":"desayuno","desc":"desayuné mate con tostadas con mermelada de durazn"},{"meal":"almuerzo","desc":"almorcé pollo al horno con papas que hizo mi vieja. mientras"},{"meal":"cena","desc":"terminé. cené fideos con salsa blanca. vi youtube hasta las 00:30 y m"}]', 6, 'desayuno: desayuné mate con tostadas con mermelada de durazn; almuerzo: almorcé pollo al horno con papas que hizo mi vieja. mientras; cena: terminé. cené fideos con salsa blanca. vi youtube hasta las 00:30 y m',
  7, 'estable', 'Buen día en todos los frentes. Subí peso en press plano.',
  3, NULL, 0, NULL, 'Facu: Análisis 2hs: derivadas parciales + gradiente (6 ej). Álgebra 1h: transformaciones lineales (teoría  | Gorila: Respondí a prospect interesado. Mandé audit de su sitio web con Claude Code. Potencial cliente.',
  NULL, NULL,
  NULL, NULL,
  8, 8,
  '2026-03-12T16:32:44.438Z', '2026-03-12T16:32:44.438Z'
);

-- Día 9: Martes 18/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-18',
  '02:00', '08:20', 6, '7:50 / 8:20. Me desperté con la alarma pero me quedé en la cama revisando WhatsApp.',
  7, NULL,
  0, NULL, NULL, 'no fui. me comió el proyecto del chatbot.',
  '[{"meal":"desayuno","desc":"desayuné mate cocido con galletitas. me senté a es"},{"meal":"almuerzo","desc":"almorcé ensalada de atún con arroz que me preparé yo solo. s"},{"meal":"cena","desc":"cené hamburguesas caseras que hice yo (pan, carne picada, le"}]', 6, 'desayuno: desayuné mate cocido con galletitas. me senté a es; almuerzo: almorcé ensalada de atún con arroz que me preparé yo solo. s; cena: cené hamburguesas caseras que hice yo (pan, carne picada, le',
  6, 'estable', 'Día productivo en código pero nulo en estudio. Me como la cabeza pensando en el parcial.',
  0.3, NULL, 0, NULL, 'Facu: Nada. Cero. 15 minutos de Análisis a la noche que no cuentan. | Gorila: Nada directo de Gorila, pero avancé en el chatbot de WhatsApp para mi familiar.',
  'Familia', NULL,
  NULL, NULL,
  5, 5,
  '2026-03-12T16:32:44.439Z', '2026-03-12T16:32:44.439Z'
);

-- Día 10: Miércoles 19/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-19',
  '00:00', '08:10', 6, '7:50 / 8:10. Me levanté con culpa por no haber estudiado ayer.',
  6, NULL,
  1, 'Espalda y bíceps', 60, 'Espalda y bíceps. Jalón 50kg (subí), remo 18kg, peso muerto 70kg, curl Z 27.5kg, dominadas 3x6.',
  '[{"meal":"desayuno","desc":"desayuné rápido, mate con tostadas. me senté con a"},{"meal":"almuerzo","desc":"almorcé milanesa napolitana con fritas (manjar). me tiré una"},{"meal":"cena","desc":"cené tarta de jamón y queso que compró mi vieja. vi un docum"}]', 6, 'desayuno: desayuné rápido, mate con tostadas. me senté con a; almuerzo: almorcé milanesa napolitana con fritas (manjar). me tiré una; cena: cené tarta de jamón y queso que compró mi vieja. vi un docum',
  8, 'motivado', 'Día de redención después de ayer. Compensé bien.',
  3.5, NULL, 0, NULL, 'Facu: Análisis 2hs: integrales por sustitución (6 ej). Álgebra 1.5hs con Facu por Meet (independencia line | Gorila: Nada.',
  'Salida', NULL,
  NULL, NULL,
  9, 9,
  '2026-03-12T16:32:44.439Z', '2026-03-12T16:32:44.439Z'
);

-- Día 11: Jueves 20/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-20',
  '01:30', '09:00', 6, '7:50 / 9:00. Dormí de más, anoche me quedé hasta tarde leyendo sobre Three.js.',
  6, NULL,
  1, 'Piernas', 45, 'Piernas liviano. Sentadilla 60kg (técnica), prensa 100kg, estocadas 10kg, curl femoral 25kg.',
  '[{"meal":"desayuno","desc":"culpable. desayuné apurado un mate con galletitas. me puse a"},{"meal":"almuerzo","desc":"almorcé fideos con pesto que me hice yo. respondí unos mails"},{"meal":"cena","desc":"cené empanadas que trajo mi vieja. abrí el apunte de análisi"}]', 6, 'desayuno: culpable. desayuné apurado un mate con galletitas. me puse a; almuerzo: almorcé fideos con pesto que me hice yo. respondí unos mails; cena: cené empanadas que trajo mi vieja. abrí el apunte de análisi',
  6, 'estable', 'La serie me comió la noche. Piernas más suaves esta vez.',
  1.7, NULL, 1, NULL, 'Facu: Álgebra 1.5hs: autovalores (teoría + 1 ej). Análisis 10 min simbólicos. | Gorila: Organicé tareas con mi socio. Pipeline de trabajo definido.',
  NULL, NULL,
  '{"series_binge":true}', 'Binge de series',
  5, 5,
  '2026-03-12T16:32:44.439Z', '2026-03-12T16:32:44.439Z'
);

-- Día 12: Viernes 21/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-21',
  NULL, '09:45', 6, 'Sin alarma / 9:45.',
  6, NULL,
  0, NULL, NULL, 'no fui, viernes.',
  '[{"meal":"desayuno","desc":"levanté, desayuné mate con facturas que trajo mi viejo. no"},{"meal":"cena","desc":"omer unas pizzas al centro de santa fe, fuimos a una pizzería de la pe"}]', 5, 'desayuno: levanté, desayuné mate con facturas que trajo mi viejo. no; cena: omer unas pizzas al centro de santa fe, fuimos a una pizzería de la pe',
  6, 'estable', 'Día social. Asado familiar + pizza con amigos. Cero académico pero necesitaba salir.',
  0, NULL, 0, NULL, 'Facu: Cero. | Gorila: Nada.',
  'Asado, Amigos, Familia, Pizza', NULL,
  NULL, NULL,
  5, 5,
  '2026-03-12T16:32:44.439Z', '2026-03-12T16:32:44.439Z'
);

-- Día 13: Sábado 22/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-22',
  '01:30', '11:00', 6, 'Sin alarma / 11:00.',
  5, NULL,
  0, NULL, NULL, 'no fui, sábado.',
  '[{"meal":"almuerzo","desc":"almorcé sobras del asado de ayer recalentadas. después me pu"},{"meal":"cena","desc":"os otras. cené empanadas de humita. me acosté a la 1:30."}]', 6, 'almuerzo: almorcé sobras del asado de ayer recalentadas. después me pu; cena: os otras. cené empanadas de humita. me acosté a la 1:30.',
  7, 'estable', 'No estudié pero invertí bien la tarde en skills de Gorila.',
  1, NULL, 0, NULL, 'Facu: Cero. | Gorila: Práctica intensiva de GSAP/ScrollTrigger. Animaciones de scroll, parallax. Muy útil para las landing',
  'Asado, Amigos', NULL,
  NULL, NULL,
  6, 6,
  '2026-03-12T16:32:44.439Z', '2026-03-12T16:32:44.439Z'
);

-- Día 14: Domingo 23/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-23',
  '23:00', '08:40', 6, '8:30 / 8:40.',
  6, NULL,
  0, NULL, NULL, 'no fui, domingo.',
  '[{"meal":"desayuno","desc":"ara misa. desayuné mate con medialunas apurado. fuimos a la"},{"meal":"almuerzo","desc":"almuerzo familiar: mi vieja hizo pollo al disco con verduras"},{"meal":"cena","desc":"critorio. cené ensalada de frutas. vi un rato youtube, un video de un"}]', 7, 'desayuno: ara misa. desayuné mate con medialunas apurado. fuimos a la; almuerzo: almuerzo familiar: mi vieja hizo pollo al disco con verduras; cena: critorio. cené ensalada de frutas. vi un rato youtube, un video de un',
  7, 'estable', 'Domingo tranquilo y productivo. Misa + familia + estudio.',
  2, NULL, 0, NULL, 'Facu: Análisis 2hs: integrales por sustitución trigonométrica (4 ej). Productivo. | Gorila: Nada.',
  'Misa, Familia', NULL,
  NULL, NULL,
  6, 6,
  '2026-03-12T16:32:44.439Z', '2026-03-12T16:32:44.439Z'
);

-- Día 15: Lunes 24/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-24',
  '00:30', '08:05', 6, '7:50 / 8:05. Arranqué la semana motivado.',
  6, NULL,
  1, 'Hombros y trapecios', 60, 'Hombros y trapecios. Press militar 30kg, laterales 8kg, face pulls, encogimientos 20kg.',
  '[{"meal":"desayuno","desc":"desayuné rápido, mate con tostadas. a las 8:30 arr"},{"meal":"almuerzo","desc":"almorcé arroz con verduras salteadas que me hice yo. mientra"},{"meal":"cena","desc":"rápidos. cené tostados de jamón y queso. me acosté a las 00:30."}]', 7, 'desayuno: desayuné rápido, mate con tostadas. a las 8:30 arr; almuerzo: almorcé arroz con verduras salteadas que me hice yo. mientra; cena: rápidos. cené tostados de jamón y queso. me acosté a las 00:30.',
  6, 'estable', 'Día equilibrado entre facu, gym y proyectos. Profe Stack empieza a tomar forma.',
  3, NULL, 0, NULL, 'Facu: Álgebra 2hs: transformaciones lineales (3 ej, 1 pendiente). Análisis 1h: integrales por partes (3 ej | Gorila: Investigué Whisper API para Profe Stack. Prueba exitosa con audio de 2 min.',
  NULL, NULL,
  NULL, NULL,
  8, 8,
  '2026-03-12T16:32:44.440Z', '2026-03-12T16:32:44.440Z'
);

-- Día 16: Martes 25/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-25',
  '02:00', '08:30', 6, '7:50 / 8:30. Costó arrancar, anoche me quedé scrolleando TikTok hasta tarde.',
  6, NULL,
  1, 'Pecho y tríceps', 60, 'Pecho y tríceps. Press 65kg (6 reps incompleto). Inclinado 16kg. Rendí mal.',
  '[{"meal":"desayuno","desc":"desayuné mate con galletitas. me senté a estudiar"},{"meal":"almuerzo","desc":"almorcé milanesas con puré. después de comer me quedé mirand"},{"meal":"cena","desc":"si todas. cené pizza fría que quedó de ayer. vi un stream de twitch y"}]', 5, 'desayuno: desayuné mate con galletitas. me senté a estudiar; almuerzo: almorcé milanesas con puré. después de comer me quedé mirand; cena: si todas. cené pizza fría que quedó de ayer. vi un stream de twitch y',
  5, 'neutro', 'Día de mucha procrastinación. TikTok e Instagram me robaron horas. Mal rendimiento en el gym también.',
  1, NULL, 1, NULL, 'Facu: Análisis ~1h: integrales impropias, 1 ej resuelto, mucha distracción. | Gorila: Nada.',
  'Asado, Salida, Pizza', NULL,
  '{"screens_late":true}', 'Pantallas/redes sociales excesivas',
  5, 5,
  '2026-03-12T16:32:44.440Z', '2026-03-12T16:32:44.440Z'
);

-- Día 17: Miércoles 26/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-26',
  '00:00', '08:00', 6, '7:50 / 8:00. Me levanté con culpa y determinación.',
  6, NULL,
  1, 'Espalda y bíceps', 60, 'Espalda y bíceps. Remo barra 55kg (subí), jalón 50kg, curl Z 27.5kg, martillo 12kg.',
  '[{"meal":"desayuno","desc":"desayuné un mate rápido y a las 8:30 ya estaba con"},{"meal":"almuerzo","desc":"almorcé tarta de verduras. estudié con facu por videollamada"},{"meal":"cena","desc":"cené ñoquis (era 26, pero los hizo mi vieja igual). estudié"}]', 7, 'desayuno: desayuné un mate rápido y a las 8:30 ya estaba con; almuerzo: almorcé tarta de verduras. estudié con facu por videollamada; cena: cené ñoquis (era 26, pero los hizo mi vieja igual). estudié',
  8, 'motivado', 'Día de redención total. Compensé el martes con creces.',
  4, NULL, 0, NULL, 'Facu: Análisis 2.5hs: integrales impropias (4 ej) + dobles (2 ej). Álgebra 1.5hs con Facu (diagonalización | Gorila: Mandé 5 mensajes de prospección a estudios de arq en Paraná.',
  'Salida', NULL,
  NULL, NULL,
  9, 9,
  '2026-03-12T16:32:44.440Z', '2026-03-12T16:32:44.440Z'
);

-- Día 18: Jueves 27/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-27',
  '01:00', '08:45', 3, '7:50 / 8:45. Dolor de espalda del gym de ayer, dormí mal por eso.',
  6, NULL,
  1, 'Piernas', 45, 'Piernas liviano (cuidando espalda). Prensa 90kg, extensiones, curl femoral, gemelos.',
  '[{"meal":"desayuno","desc":"olestaba. desayuné lento, mate con medialunas. me puse a est"},{"meal":"almuerzo","desc":"almorcé pollo con arroz. después me puse a investigar liveki"},{"meal":"cena","desc":"cené empanadas de jamón y queso. antes de dormir abrí el apu"}]', 6, 'desayuno: olestaba. desayuné lento, mate con medialunas. me puse a est; almuerzo: almorcé pollo con arroz. después me puse a investigar liveki; cena: cené empanadas de jamón y queso. antes de dormir abrí el apu',
  5, 'neutro', 'Serie me atrapó de nuevo. Espalda molesta pero nada grave.',
  1.7, NULL, 1, NULL, 'Facu: Álgebra 1.5hs: diagonalización de matrices 3x3 (2 ej). Análisis 10 min de lectura. | Gorila: Investigué LiveKit para Profe Stack. Viable para las videollamadas.',
  NULL, NULL,
  '{"screens_late":true,"series_binge":true}', 'Pantallas/redes sociales excesivas; Binge de series',
  5, 5,
  '2026-03-12T16:32:44.440Z', '2026-03-12T16:32:44.440Z'
);

-- Día 19: Viernes 28/02
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-02-28',
  NULL, '10:00', 6, 'Sin alarma / 10:00.',
  5, NULL,
  0, NULL, NULL, 'no fui.',
  '[{"meal":"desayuno","desc":"levanté, desayuné mate con facturas escuchando música. jugu"},{"meal":"almuerzo","desc":"almorcé milanesas en familia. mi vieja preguntó cómo iba gor"}]', 5, 'desayuno: levanté, desayuné mate con facturas escuchando música. jugu; almuerzo: almorcé milanesas en familia. mi vieja preguntó cómo iba gor',
  6, 'estable', 'Viernes de desconexión social. FIFA + bar.',
  0, NULL, 0, NULL, 'Facu: Nada. | Gorila: Nada directo, pero charla con la familia sobre el negocio.',
  'Amigos, Salida, Familia, FIFA', NULL,
  '{"alcohol":true}', 'Alcohol',
  4, 4,
  '2026-03-12T16:32:44.440Z', '2026-03-12T16:32:44.440Z'
);

-- Día 20: Sábado 01/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-01',
  '01:00', '11:30', 4, 'Sin alarma / 11:30. Destruido.',
  4, NULL,
  0, NULL, NULL, 'no fui.',
  '[{"meal":"almuerzo","desc":"almorcé sobras recalentadas. me puse a investigar el servici"},{"meal":"cena","desc":", ranked. cené un lomito que pedimos por delivery. me dormí tipo 1:00."}]', 6, 'almuerzo: almorcé sobras recalentadas. me puse a investigar el servici; cena: , ranked. cené un lomito que pedimos por delivery. me dormí tipo 1:00.',
  7, 'estable', 'Productivo en proyectos, nulo en estudio. Tengo que ponerme las pilas con la facu.',
  1, NULL, 1, NULL, 'Facu: Nada. | Gorila: Investigación WhatsApp bulk messaging (Web vs API). Remotion: template de video con subtítulos + fil',
  'Amigos', NULL,
  '{"screens_late":true}', 'Pantallas/redes sociales excesivas',
  4, 4,
  '2026-03-12T16:32:44.440Z', '2026-03-12T16:32:44.440Z'
);

-- Día 21: Domingo 02/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-02',
  '23:00', '08:30', 6, '8:30 / 8:30. Me levanté de una, domingo de misa.',
  8, NULL,
  0, NULL, NULL, 'no fui, domingo.',
  '[{"meal":"desayuno","desc":"desayuné mate con facturas que compré yo ayer. fui"},{"meal":"almuerzo","desc":"almuerzo familiar grande: vinieron mis abuelos, mi vieja hiz"},{"meal":"cena","desc":"cené liviano, yogur con cereales. armé un resumen rápido de"}]', 6, 'desayuno: desayuné mate con facturas que compré yo ayer. fui; almuerzo: almuerzo familiar grande: vinieron mis abuelos, mi vieja hiz; cena: cené liviano, yogur con cereales. armé un resumen rápido de',
  8, 'motivado', 'Domingo lindo con familia. Misa me hizo reflexionar. Estudio productivo.',
  2.5, NULL, 0, NULL, 'Facu: Análisis 2hs: repaso general de integrales, cuadro resumen de métodos. Álgebra 30min: resumen de tem | Gorila: Nada.',
  'Asado, Misa, Familia', NULL,
  NULL, NULL,
  7, 7,
  '2026-03-12T16:32:44.440Z', '2026-03-12T16:32:44.440Z'
);

-- Día 22: Lunes 03/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-03',
  '23:00', '07:35', 7, '7:30 / 7:35. Me levanté temprano porque HOY ES EL PARCIAL DE ANÁLISIS.',
  6, NULL,
  1, 'Pecho y tríceps', 45, 'Pecho liviano para descargar. Press 50kg suave, aperturas, tríceps.',
  '[{"meal":"desayuno","desc":"los ojos. desayuné mate con tostadas, intenté repasar 30 min"},{"meal":"almuerzo","desc":"aturdido. almorcé tarde en casa tipo 13:30, mi vieja me había guardado"},{"meal":"cena","desc":"o. volví, cené milanesa de vuelta (había sobrado). me dormí temprano,"}]', 6, 'desayuno: los ojos. desayuné mate con tostadas, intenté repasar 30 min; almuerzo: aturdido. almorcé tarde en casa tipo 13:30, mi vieja me había guardado; cena: o. volví, cené milanesa de vuelta (había sobrado). me dormí temprano,',
  7, 'estable', 'Día de parcial. Desgaste mental total. Me dormí temprano.',
  0, NULL, 0, NULL, 'Facu: PARCIAL DE ANÁLISIS. 5 ejercicios. Sensación mixta. A esperar resultados. | Gorila: Nada.',
  NULL, NULL,
  NULL, NULL,
  6, 6,
  '2026-03-12T16:32:44.440Z', '2026-03-12T16:32:44.440Z'
);

-- Día 23: Martes 04/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-04',
  '00:30', '09:00', 6, '7:50 / 9:00. Post-parcial, me permití dormir de más.',
  6, NULL,
  1, 'Espalda y bíceps', 60, 'Espalda y bíceps. Remo 55kg, jalón 50kg, face pulls, curl Z, martillo.',
  '[{"meal":"desayuno","desc":"desayuné tranquilo, mate con galletitas. me sentí"},{"meal":"almuerzo","desc":"almorcé fideos con crema y champiñones. seguí con la propues"},{"meal":"cena","desc":"cené tarta de atún que compró mi vieja. jugué counter un rat"}]', 6, 'desayuno: desayuné tranquilo, mate con galletitas. me sentí; almuerzo: almorcé fideos con crema y champiñones. seguí con la propues; cena: cené tarta de atún que compró mi vieja. jugué counter un rat',
  7, 'estable', 'Buen día laboral. La propuesta quedó prolija. A esperar respuesta del cliente.',
  1, NULL, 0, NULL, 'Facu: Nada. Post-parcial. | Gorila: Armé propuesta completa para estudio de arq de Paraná: audit, mockups, precios. La mandé.',
  'Salida', NULL,
  NULL, NULL,
  7, 7,
  '2026-03-12T16:32:44.441Z', '2026-03-12T16:32:44.441Z'
);

-- Día 24: Miércoles 05/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-05',
  '00:00', '08:10', 4, '7:50 / 8:10.',
  7, NULL,
  1, 'Piernas', 60, 'Piernas. Sentadilla 75kg 4x6 (NUEVO PESO). Prensa 130kg. Estocadas 12kg.',
  '[{"meal":"desayuno","desc":"desayuné mate con tostadas. me puse a estudiar álg"},{"meal":"almuerzo","desc":"almorcé arroz con pollo recalentado. estudié con facu por me"},{"meal":"cena","desc":"estruido. cené liviano, un yogur con granola. me puse a laburar un poc"}]', 7, 'desayuno: desayuné mate con tostadas. me puse a estudiar álg; almuerzo: almorcé arroz con pollo recalentado. estudié con facu por me; cena: estruido. cené liviano, un yogur con granola. me puse a laburar un poc',
  8, 'motivado', 'Día pesado pero productivo. Sentadilla 75kg es un logro.',
  4.5, NULL, 0, NULL, 'Facu: Álgebra 3hs: diagonalización intensiva (3 ej completos). + 1.5hs con Facu. Día fuerte. | Gorila: Fix de bug en chatbot WhatsApp (parseo de emojis).',
  NULL, NULL,
  NULL, NULL,
  8, 8,
  '2026-03-12T16:32:44.441Z', '2026-03-12T16:32:44.441Z'
);

-- Día 25: Jueves 06/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-06',
  '01:30', '08:50', 4, '7:50 / 8:50. Dormí pésimo, me quedé viendo la serie hasta las 2.',
  6, NULL,
  1, 'Hombros y trapecios', 60, 'Hombros. Press militar 32kg (subí), laterales 10kg, pájaros 8kg, face pulls.',
  '[{"meal":"desayuno","desc":"de ayer. desayuné mate amargo y unas galletitas. intenté es"},{"meal":"almuerzo","desc":"almorcé empanadas que compró mi vieja. me tiré una siesta pe"},{"meal":"cena","desc":"cené pizza que pidió mi viejo por delivery. vi la serie, est"}]', 5, 'desayuno: de ayer. desayuné mate amargo y unas galletitas. intenté es; almuerzo: almorcé empanadas que compró mi vieja. me tiré una siesta pe; cena: cené pizza que pidió mi viejo por delivery. vi la serie, est',
  7, 'estable', 'Día lento en lo académico. Rescaté la tarde con gym y research.',
  1, NULL, 0, NULL, 'Facu: Cero. No pude concentrarme. | Gorila: Investigué Mercado Pago SDK para Profe Stack. Leí sobre ARCA/AFIP facturación.',
  'Pizza', NULL,
  NULL, NULL,
  6, 6,
  '2026-03-12T16:32:44.441Z', '2026-03-12T16:32:44.441Z'
);

-- Día 26: Viernes 07/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-07',
  NULL, '10:00', 6, 'Sin alarma / 10:00.',
  5, NULL,
  0, NULL, NULL, 'no fui.',
  '[{"meal":"desayuno","desc":"e encima. desayuné mate con facturas celebrando solo en la c"},{"meal":"almuerzo","desc":"celebrar, almorcé contento. le conté a mi viejo cuando llegó del labur"}]', 6, 'desayuno: e encima. desayuné mate con facturas celebrando solo en la c; almuerzo: celebrar, almorcé contento. le conté a mi viejo cuando llegó del labur',
  9, 'motivado', 'DÍA DE FESTEJO. Aprobé el parcial. Costanera + boliche.',
  0, NULL, 0, 'APROBÉ ANÁLISIS CON 7.', 'Facu: APROBÉ ANÁLISIS CON 7. Un parcial menos. | Gorila: Nada.',
  'Amigos, Salida, Costanera', NULL,
  '{"alcohol":true}', 'Alcohol',
  5, 5,
  '2026-03-12T16:32:44.441Z', '2026-03-12T16:32:44.441Z'
);

-- Día 27: Sábado 08/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-08',
  '01:00', '11:00', 4, 'Sin alarma / 11:00. Resaca.',
  3, NULL,
  0, NULL, NULL, 'no fui.',
  '[{"meal":"almuerzo","desc":"almorcé sobras, no tenía ganas de cocinar ni de nada. tipo 1"},{"meal":"cena","desc":"ón larga. cené hamburguesas caseras. me dormí tipo 1:00."}]', 5, 'almuerzo: almorcé sobras, no tenía ganas de cocinar ni de nada. tipo 1; cena: ón larga. cené hamburguesas caseras. me dormí tipo 1:00.',
  6, 'estable', 'Día de coding personal y recuperación de resaca.',
  1, NULL, 0, NULL, 'Facu: Nada. | Gorila: HaxBall mod: chat grupal con Supabase realtime. Remotion: avancé en pipeline de video automático.',
  'Amigos', NULL,
  '{"alcohol":true}', 'Alcohol',
  5, 5,
  '2026-03-12T16:32:44.441Z', '2026-03-12T16:32:44.441Z'
);

-- Día 28: Domingo 09/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-09',
  '23:00', '08:35', 6, '8:30 / 8:35.',
  6, NULL,
  0, NULL, NULL, 'no fui, domingo.',
  '[{"meal":"desayuno","desc":"acturas y café con leche para desayunar/merendar post-misa."},{"meal":"cena","desc":"ntensivo. cené ensalada. me dormí a las 23:00."}]', 7, 'desayuno: acturas y café con leche para desayunar/merendar post-misa.; cena: ntensivo. cené ensalada. me dormí a las 23:00.',
  7, 'estable', 'Domingo recargado. Misa, asado, estudio. Semana de parcial viene.',
  2, NULL, 0, NULL, 'Facu: Álgebra 2hs: producto interno, Gram-Schmidt (3 ej). Adelantando para el parcial del jueves. | Gorila: Le expliqué Profe Stack a mi viejo. Feedback positivo = motivación.',
  'Asado, Misa, Familia', NULL,
  NULL, NULL,
  6, 6,
  '2026-03-12T16:32:44.441Z', '2026-03-12T16:32:44.441Z'
);

-- Día 29: Lunes 10/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-10',
  '00:30', '08:00', 6, '7:50 / 8:00. Arranqué motivado, semana de parcial.',
  6, NULL,
  1, 'Pecho', 60, 'Pecho pesado. PRESS PLANO 70KG x1 (NUEVO RM). Inclinado 18kg. Gran día.',
  '[{"meal":"desayuno","desc":"desayuné rápido, mate con tostadas. a las 8:30 cla"},{"meal":"almuerzo","desc":"almorcé tarta de atún. revisé el celu: el estudio de arquite"},{"meal":"cena","desc":"cené ñoquis que hizo mi vieja. seguí laburando en el sitio u"}]', 6, 'desayuno: desayuné rápido, mate con tostadas. a las 8:30 cla; almuerzo: almorcé tarta de atún. revisé el celu: el estudio de arquite; cena: cené ñoquis que hizo mi vieja. seguí laburando en el sitio u',
  10, 'motivado', 'GRAN DÍA. Cliente cerrado + 70kg en press. Uno de los mejores días del mes.',
  3, NULL, 0, 'Primer cliente cerrado', 'Facu: Análisis 2hs: series de potencias (2 ej). Álgebra 1h: repaso diagonalización. | Gorila: PRIMER CLIENTE CERRADO. Estudio de arq de Paraná. USD 100 + 20/mes. Empecé el sitio en Next.js + GSA',
  NULL, NULL,
  NULL, NULL,
  8, 8,
  '2026-03-12T16:32:44.441Z', '2026-03-12T16:32:44.441Z'
);

-- Día 30: Martes 11/03
INSERT INTO daily_entries (
  user_id, date,
  bedtime, wake_time, sleep_quality, sleep_note,
  energy_level, energy_note,
  exercise_done, exercise_type, exercise_duration, exercise_note,
  diet_entries, diet_quality, diet_note,
  mood, emotional_state, emotional_note,
  focus_hours, tasks_completed, procrastination, biggest_win, productivity_note,
  social_event, relationships_note,
  vices_details, vices_note,
  overall_score, day_rating,
  created_at, updated_at
) VALUES (
  1, '2025-03-11',
  '00:00', '08:15', 6, '7:50 / 8:15.',
  6, NULL,
  1, 'Espalda y bíceps', 60, 'Espalda y bíceps. Remo 55kg, jalón 52.5kg (subí), dominadas 3x7 (+1), curl Z 30kg.',
  '[{"meal":"desayuno","desc":"de ayer. desayuné mate con medialunas. me puse a estudiar á"},{"meal":"almuerzo","desc":"almorcé fideos con bolognesa que hice yo (sale una receta bu"},{"meal":"cena","desc":"cené milanesa con ensalada. estudié álgebra un ratito más, h"}]', 7, 'desayuno: de ayer. desayuné mate con medialunas. me puse a estudiar á; almuerzo: almorcé fideos con bolognesa que hice yo (sale una receta bu; cena: cené milanesa con ensalada. estudié álgebra un ratito más, h',
  10, 'motivado', 'Buen cierre de mes. Aprobé parcial, cerré cliente, gym progresando. Viene el parcial de Álgebra el jueves. A meterle.',
  2.5, NULL, 0, NULL, 'Facu: Álgebra 2.5hs: Gram-Schmidt intensivo (4 ej). Resumen de fórmulas para parcial. | Gorila: Reunión con socio, división de tareas del proyecto. Avancé sección de proyectos del sitio.',
  NULL, NULL,
  NULL, NULL,
  7, 7,
  '2026-03-12T16:32:44.442Z', '2026-03-12T16:32:44.442Z'
);

-- ── Habit Logs (Gym + Rezo) ─────────────────────────────
-- NOTE: These require habit IDs to exist first. Run these
-- after creating the habits via the bot or manually.
-- Gym habit = ID 1, Rezo habit = ID 2 (adjust as needed)

-- Lunes 10/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-10', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-10', 1, '2026-03-12T16:32:44.442Z');

-- Martes 11/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-11', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-11', 0, '2026-03-12T16:32:44.442Z');

-- Miércoles 12/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-12', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-12', 1, '2026-03-12T16:32:44.442Z');

-- Jueves 13/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-13', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-13', 1, '2026-03-12T16:32:44.442Z');

-- Viernes 14/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-14', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-14', 0, '2026-03-12T16:32:44.442Z');

-- Sábado 15/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-15', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-15', 1, '2026-03-12T16:32:44.442Z');

-- Domingo 16/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-16', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-16', 1, '2026-03-12T16:32:44.442Z');

-- Lunes 17/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-17', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-17', 1, '2026-03-12T16:32:44.442Z');

-- Martes 18/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-18', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-18', 0, '2026-03-12T16:32:44.442Z');

-- Miércoles 19/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-19', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-19', 1, '2026-03-12T16:32:44.442Z');

-- Jueves 20/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-20', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-20', 1, '2026-03-12T16:32:44.442Z');

-- Viernes 21/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-21', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-21', 0, '2026-03-12T16:32:44.442Z');

-- Sábado 22/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-22', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-22', 1, '2026-03-12T16:32:44.442Z');

-- Domingo 23/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-23', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-23', 1, '2026-03-12T16:32:44.442Z');

-- Lunes 24/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-24', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-24', 1, '2026-03-12T16:32:44.442Z');

-- Martes 25/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-25', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-25', 0, '2026-03-12T16:32:44.442Z');

-- Miércoles 26/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-26', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-26', 1, '2026-03-12T16:32:44.442Z');

-- Jueves 27/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-27', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-27', 1, '2026-03-12T16:32:44.442Z');

-- Viernes 28/02
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-02-28', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-02-28', 0, '2026-03-12T16:32:44.442Z');

-- Sábado 01/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-01', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-01', 1, '2026-03-12T16:32:44.442Z');

-- Domingo 02/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-02', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-02', 1, '2026-03-12T16:32:44.442Z');

-- Lunes 03/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-03', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-03', 1, '2026-03-12T16:32:44.442Z');

-- Martes 04/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-04', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-04', 1, '2026-03-12T16:32:44.442Z');

-- Miércoles 05/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-05', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-05', 1, '2026-03-12T16:32:44.442Z');

-- Jueves 06/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-06', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-06', 0, '2026-03-12T16:32:44.442Z');

-- Viernes 07/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-07', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-07', 0, '2026-03-12T16:32:44.442Z');

-- Sábado 08/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-08', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-08', 1, '2026-03-12T16:32:44.442Z');

-- Domingo 09/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-09', 0, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-09', 1, '2026-03-12T16:32:44.442Z');

-- Lunes 10/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-10', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-10', 1, '2026-03-12T16:32:44.442Z');

-- Martes 11/03
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (1, 1, '2025-03-11', 1, '2026-03-12T16:32:44.442Z');
-- INSERT INTO habit_logs (habit_id, user_id, date, completed, created_at) VALUES (2, 1, '2025-03-11', 1, '2026-03-12T16:32:44.442Z');

-- ── Patterns / Correlations ──────────────────────────────

INSERT INTO patterns (
  user_id, pattern_type, area_a, area_b, description, correlation, data_points, confidence, active, created_at, updated_at
) VALUES (
  1, 'correlation', 'exercise', 'mood', 'Gym mejora ánimo: promedio mood gym=7.2 vs no-gym=6.9', 0.066, 30, 0.7, 1, '2026-03-12T16:32:44.442Z', '2026-03-12T16:32:44.442Z'
);

INSERT INTO patterns (
  user_id, pattern_type, area_a, area_b, description, correlation, data_points, confidence, active, created_at, updated_at
) VALUES (
  1, 'correlation', 'exercise', 'energy', 'Gym mejora energía: promedio energy gym=6.2 vs no-gym=5.6', 0.109, 30, 0.7, 1, '2026-03-12T16:32:44.442Z', '2026-03-12T16:32:44.442Z'
);

INSERT INTO patterns (
  user_id, pattern_type, area_a, area_b, description, correlation, data_points, confidence, active, created_at, updated_at
) VALUES (
  1, 'correlation', 'vices', 'productivity', 'Procrastinación baja focus: promedio hs con=1.2 vs sin=1.8', -0.123, 30, 0.65, 1, '2026-03-12T16:32:44.442Z', '2026-03-12T16:32:44.442Z'
);

INSERT INTO patterns (
  user_id, pattern_type, area_a, area_b, description, correlation, data_points, confidence, active, created_at, updated_at
) VALUES (
  1, 'correlation', 'sleep', 'productivity', 'Levantarse temprano (<=8am) mejora focus: 2.2hs vs tarde (>=9am): 0.6hs', 0.331, 30, 0.6, 1, '2026-03-12T16:32:44.442Z', '2026-03-12T16:32:44.442Z'
);

INSERT INTO patterns (
  user_id, pattern_type, area_a, area_b, description, correlation, data_points, confidence, active, created_at, updated_at
) VALUES (
  1, 'trend', 'exercise', 'exercise', 'Gym 4x/semana consistente. Press plano progresó: 60kg -> 65kg -> 70kg RM en 30 días.', 0.850, 30, 0.9, 1, '2026-03-12T16:32:44.442Z', '2026-03-12T16:32:44.442Z'
);

INSERT INTO patterns (
  user_id, pattern_type, area_a, area_b, description, correlation, data_points, confidence, active, created_at, updated_at
) VALUES (
  1, 'trend', 'productivity', 'productivity', 'Patrón: viernes/sábado = cero estudio. Lunes-miércoles más productivos.', 0.000, 30, 0.85, 1, '2026-03-12T16:32:44.442Z', '2026-03-12T16:32:44.442Z'
);

INSERT INTO patterns (
  user_id, pattern_type, area_a, area_b, description, correlation, data_points, confidence, active, created_at, updated_at
) VALUES (
  1, 'anomaly', 'mood', 'productivity', 'Día 29 (lunes 10/03) fue outlier positivo: primer cliente + 70kg RM + buen estudio = mood 10.', 0.950, 1, 0.95, 1, '2026-03-12T16:32:44.442Z', '2026-03-12T16:32:44.442Z'
);

COMMIT;

-- ═══════════════════════════════════════════════════════
-- SUMMARY STATS
-- Total days: 30
-- Gym days: 16
-- Avg mood: 7.0
-- Avg energy: 5.9
-- Avg focus hours: 1.7
-- Days with procrastination: 7
-- Avg overall score: 6.1
-- ═══════════════════════════════════════════════════════